name: Generate data

on:
  push:

jobs:
  say:
    runs-on: ubuntu-latest
    steps:
    - name: print fs
      run: echo $(ls)
    - name: setup 
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: create a file
      run: npm run generate
    - name: check fs again
      run: echo $(ls)
    - name: print pwd
      run: echo $(pwd)
    - name: read from file
      run: |
        #!/bin/bash
        value=`cat sample.txt`
        echo $value