name: "Create PR"
on: push

jobs:
  generate files:
    runs-on: ubuntu-latest
    steps:
    uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    run: |
      npm generate
      git add .
      git commit -m "generated files"

  create-pr-on-push:
    needs: generate files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: ${{ github.ref }}
        base: main
        title: "An automatically created PR!"