name: Generate data

on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: print fs
      run: echo $(ls)
    - name: setup 
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: create a file
      run: npm run generate
    - name: check fs again
      run: echo $(ls)
    - name: print pwd
      run: echo $(pwd)
    - name: read from file
      run: |
        #!/bin/bash
        value=`cat sample.txt`
        echo $value
    - name: upload data
      uses: actions/upload-artifact@v2
      with:
        name: sample
        path: sample.txt
  commit:
    needs: generate
    runs-on: ubuntu-latest
    steps:
    - name: Download sample
      uses: actions/download-artifact@v2
      with:
        name: sample
        path: .
    - name: print fs
      run: echo $(ls)
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        branch: generated
    - name: Checkout
      uses: actions/checkout@v2
    - name: commit
      run: |
        echo $(pwd)
        echo $(ls)
        git add .
        git commit -m "generated files"
        git push
    - name: Mkr PR to master
      if: ${{ steps.commit.outputs.status }}
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        head: generated
        title: "Update generated files"
        body: "Communicate the changes"
  


