name: Generate data

on:
  push:

jobs:
  say:
    runs-on: ubuntu-latest
    steps:
    - name: print fs
      run: echo $(ls)
    - name: create a file
      run: touch info.txt
    - name: check fs again
      run: echo $(ls)
    - name: print pwd
      run: echo $(pwd)
  read_file:
    runs-on: ubuntu-latest
    steps:
    - name: read from file
      run: |
        #!/bin/bash
        value=`cat config.txt`
        echo $value